// <auto-generated />
using System;
using Lab3.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab3.Model.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260506161117_InitialWithData")]
    partial class InitialWithData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab1.Model.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "marko@adriatic.hr",
                            FirstName = "Marko",
                            HireDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 1,
                            LastName = "Maric",
                            PhoneNumber = "0991111111",
                            Role = 1,
                            Salary = 1200m
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivana@sunset.hr",
                            FirstName = "Ivana",
                            HireDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 2,
                            LastName = "Ivic",
                            PhoneNumber = "0992222222",
                            Role = 2,
                            Salary = 1000m
                        },
                        new
                        {
                            Id = 3,
                            Email = "petra@mountain.hr",
                            FirstName = "Petra",
                            HireDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HotelId = 3,
                            LastName = "Peric",
                            PhoneNumber = "0993333333",
                            Role = 3,
                            Salary = 900m
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1999, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "HR12345",
                            Email = "ivan@gmail.com",
                            FirstName = "Ivan",
                            LastName = "Ivic",
                            PhoneNumber = "0951111111"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2000, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "HR67890",
                            Email = "ana@gmail.com",
                            FirstName = "Ana",
                            LastName = "Anic",
                            PhoneNumber = "0952222222"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1998, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentNumber = "HR54321",
                            Email = "luka@gmail.com",
                            FirstName = "Luka",
                            LastName = "Lukic",
                            PhoneNumber = "0953333333"
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 10",
                            City = "Zagreb",
                            Name = "Adriatic Hotel",
                            PhoneNumber = "0911111111",
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Address = "Riva 20",
                            City = "Split",
                            Name = "Sunset Resort",
                            PhoneNumber = "0922222222",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Korzo 5",
                            City = "Rijeka",
                            Name = "Mountain View Hotel",
                            PhoneNumber = "0933333333",
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 400m,
                            IsPaid = true,
                            PaymentDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 2,
                            ReservationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 600m,
                            IsPaid = true,
                            PaymentDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 1,
                            ReservationId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 750m,
                            IsPaid = false,
                            PaymentDate = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 2,
                            ReservationId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 540m,
                            IsPaid = false,
                            PaymentDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = 1,
                            ReservationId = 4
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("HotelId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckInDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            ReservationCode = "RES001",
                            ReservationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 1,
                            Status = 2,
                            TotalPrice = 400m
                        },
                        new
                        {
                            Id = 2,
                            CheckInDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 2,
                            ReservationCode = "RES002",
                            ReservationDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 2,
                            Status = 2,
                            TotalPrice = 600m
                        },
                        new
                        {
                            Id = 3,
                            CheckInDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            ReservationCode = "RES003",
                            ReservationDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 3,
                            Status = 1,
                            TotalPrice = 750m
                        },
                        new
                        {
                            Id = 4,
                            CheckInDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            ReservationCode = "RES004",
                            ReservationDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoomId = 4,
                            Status = 3,
                            TotalPrice = 540m
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("HotelId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent service and clean rooms.",
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 1,
                            HotelId = 1,
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Very nice spa experience.",
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestId = 3,
                            HotelId = 2,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricePerNight")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Floor = 1,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 80m,
                            RoomNumber = "101",
                            RoomType = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Floor = 1,
                            HotelId = 1,
                            IsAvailable = true,
                            PricePerNight = 120m,
                            RoomNumber = "102",
                            RoomType = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 3,
                            Floor = 2,
                            HotelId = 2,
                            IsAvailable = false,
                            PricePerNight = 250m,
                            RoomNumber = "201",
                            RoomType = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 2,
                            Floor = 2,
                            HotelId = 2,
                            IsAvailable = true,
                            PricePerNight = 150m,
                            RoomNumber = "202",
                            RoomType = 2
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1,
                            Floor = 3,
                            HotelId = 3,
                            IsAvailable = true,
                            PricePerNight = 70m,
                            RoomNumber = "301",
                            RoomType = 1
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 3,
                            Floor = 3,
                            HotelId = 3,
                            IsAvailable = false,
                            PricePerNight = 180m,
                            RoomNumber = "302",
                            RoomType = 3
                        });
                });

            modelBuilder.Entity("Lab1.Model.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Buffet breakfast",
                            HotelId = 1,
                            IsAvailable = true,
                            Name = "Breakfast",
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Private hotel parking",
                            HotelId = 1,
                            IsAvailable = true,
                            Name = "Parking",
                            Price = 10m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Spa and wellness access",
                            HotelId = 2,
                            IsAvailable = true,
                            Name = "Spa",
                            Price = 30m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Hotel restaurant dinner",
                            HotelId = 3,
                            IsAvailable = true,
                            Name = "Dinner",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("ReservationService", b =>
                {
                    b.Property<int>("ReservationsId")
                        .HasColumnType("int");

                    b.Property<int>("ServicesId")
                        .HasColumnType("int");

                    b.HasKey("ReservationsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ReservationService");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Employee", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Hotel", "Hotel")
                        .WithMany("Employees")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Payment", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Reservation", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab1.Model.Entities.Hotel", null)
                        .WithMany("Reservations")
                        .HasForeignKey("HotelId");

                    b.HasOne("Lab1.Model.Entities.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Review", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Guest", "Guest")
                        .WithMany("Reviews")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab1.Model.Entities.Hotel", "Hotel")
                        .WithMany("Reviews")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Room", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Service", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Hotel", "Hotel")
                        .WithMany("Services")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("ReservationService", b =>
                {
                    b.HasOne("Lab1.Model.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab1.Model.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab1.Model.Entities.Guest", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Hotel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("Rooms");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Reservation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Lab1.Model.Entities.Room", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
